title: Elena Abramova # your name (or website title) here
logo: "https://github.com/ElenaAb1405/myportfolio/blob/454ba5710b1a05c15502823394274e2b186e81f4/images/photo_logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br> Experienced digital technology enthusiast with a track record of cutting-edge innovations in Russia’s top digital retail,
  telecommunication and fintech ecosystems. Visionary leader and expert in product building, analytics and customer support, shifting
  leading enterprises to Data Science practices to improve business results effectively. <br>
  
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/elena-abramova-5a1970242/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-54516992-1 # your Google Analytics tracking ID here
